spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory
          use_query_cache: true
        hbm2ddl:
          import_files: #schema.sql
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123